import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial21757535054161 implements MigrationInterface {
    name = 'Initial21757535054161'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "gc_cms_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "password" text NOT NULL, "first_name" character varying(255) NOT NULL, "last_name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "phone_number" character varying(20), "last_login" TIMESTAMP, "account_status" character varying(50) NOT NULL DEFAULT 'Active', "status" character varying(50), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "profile_picture" character varying, "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_0bfcfd82e7868e6e3fae9c47503" UNIQUE ("email"), CONSTRAINT "PK_463731af6b3bf3e1c6954c8c75d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "session" ("id" SERIAL NOT NULL, "hash" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "user_id" uuid, CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_30e98e8746699fb9af235410af" ON "session" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "charge_terms" ("charge_term_id" SERIAL NOT NULL, "charge_term_code" character varying(50) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b936714a4f868817df25e2b318d" PRIMARY KEY ("charge_term_id"))`);
        await queryRunner.query(`CREATE TABLE "charge_term_names" ("charge_term_name_id" SERIAL NOT NULL, "charge_term_name" character varying(100) NOT NULL, "charge_term_id" integer NOT NULL, "charge_class_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a38b289dd8db372d7f131fecbaa" PRIMARY KEY ("charge_term_name_id"))`);
        await queryRunner.query(`CREATE TABLE "charge_types" ("charge_type_id" SERIAL NOT NULL, "charge_type_code" character varying(50) NOT NULL, "charge_type_name" character varying(100) NOT NULL, "charge_class_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9fc1c4b91507652bcd0c6133f6b" PRIMARY KEY ("charge_type_id"))`);
        await queryRunner.query(`CREATE TABLE "charge_classes" ("charge_class_id" SERIAL NOT NULL, "charge_class_code" character varying(50) NOT NULL, "charge_class_name" character varying(100) NOT NULL, "multiplier" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aca0814ae3bef136ca35eac2f1d" PRIMARY KEY ("charge_class_id"))`);
        await queryRunner.query(`CREATE TABLE "charge_categories" ("charge_category_id" SERIAL NOT NULL, "charge_category_code" character varying(50) NOT NULL, "charge_category_name" character varying(100) NOT NULL, "charge_class_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_17679bb934fef8327581a1b1542" PRIMARY KEY ("charge_category_id"))`);
        await queryRunner.query(`CREATE TABLE "charges" ("charge_id" SERIAL NOT NULL, "charge_code" character varying(50) NOT NULL, "charge_description" character varying(255) NOT NULL, "charge_amount" numeric(10,4), "charge_perc" numeric(10,4), "greenpower_perc" numeric(10,4), "reference_01" character varying(100), "plan_id" integer NOT NULL, "charge_type_id" integer, "charge_category_id" integer, "charge_term_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7162114fae098bae48474a13b2e" PRIMARY KEY ("charge_id"))`);
        await queryRunner.query(`CREATE TABLE "plan_types" ("plan_type_id" SERIAL NOT NULL, "plan_type_code" character varying(50) NOT NULL, "plan_type_name" character varying(100) NOT NULL, CONSTRAINT "PK_efa08be4d37d5bab42b2da3ceaa" PRIMARY KEY ("plan_type_id"))`);
        await queryRunner.query(`CREATE TABLE "zones" ("zone_id" SERIAL NOT NULL, "zone_code" character varying(50) NOT NULL, "zone_name" character varying(100) NOT NULL, "supply_areas" text, CONSTRAINT "PK_b536906901e675e2e30fe819542" PRIMARY KEY ("zone_id"))`);
        await queryRunner.query(`CREATE TABLE "fuel_types" ("fuel_type_id" SERIAL NOT NULL, "fuel_type_code" character varying(10) NOT NULL, "fuel_type_name" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fda4367c7d61155d7a3b33988b9" PRIMARY KEY ("fuel_type_id"))`);
        await queryRunner.query(`CREATE TABLE "tariff_types" ("tariff_type_id" SERIAL NOT NULL, "tariff_type_code" character varying(20) NOT NULL, "tariff_type_name" character varying(100) NOT NULL, "fuel_type_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d8d1de892e7e01516fb7b2ca4e1" PRIMARY KEY ("tariff_type_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_categories" ("rate_category_id" SERIAL NOT NULL, "rate_category_code" character varying(20) NOT NULL, "rate_category_name" character varying(100) NOT NULL, "allow_multi_seasons" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f31c4079f1748cba20f354f809b" PRIMARY KEY ("rate_category_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_item_blocks" ("rate_item_block_id" SERIAL NOT NULL, "block_number" integer NOT NULL, "block_rate" numeric(10,8) NOT NULL, "block_consumption" numeric(10,8), "rate_item_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_66cddb647aadaaef12a610bb17a" PRIMARY KEY ("rate_item_block_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_periods" ("rate_period_id" SERIAL NOT NULL, "rate_period_code" character varying(50) NOT NULL, "rate_period_name" character varying(100) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f8fc102f1e7a9757bb6fab8fce8" PRIMARY KEY ("rate_period_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_item_demands" ("rate_item_demand_id" SERIAL NOT NULL, "min_kw" numeric(10,8) NOT NULL, "max_kw" numeric(10,8), "charge" numeric(10,8) NOT NULL, "rate_item_id" integer, "measurement_period_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_605581eaac2356a1e98ce394f5" UNIQUE ("rate_item_id"), CONSTRAINT "PK_4338b8b049b95d019562c476bbd" PRIMARY KEY ("rate_item_demand_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_item_timings" ("rate_item_timing_id" SERIAL NOT NULL, "time_band_start" TIME NOT NULL, "time_band_end" TIME NOT NULL, "weekdays" boolean DEFAULT false, "weekend_sat" boolean DEFAULT false, "weekend_sun" boolean DEFAULT false, "rate_item_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9fd6448c7199c9fe22f2e480760" PRIMARY KEY ("rate_item_timing_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_classes" ("rate_class_id" SERIAL NOT NULL, "rate_class_code" character varying(20) NOT NULL, "rate_class_name" character varying(100) NOT NULL, "validate_24_hour_timing" boolean NOT NULL DEFAULT false, "multiplier" integer NOT NULL DEFAULT '1', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7a72412200c035badf005b54541" PRIMARY KEY ("rate_class_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_types" ("rate_type_id" SERIAL NOT NULL, "rate_type_code" character varying(20) NOT NULL, "rate_type_name" character varying(100) NOT NULL, "has_timings" boolean NOT NULL DEFAULT false, "rate_class_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1f342e2ef9431881e5d7c44fc48" PRIMARY KEY ("rate_type_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_items" ("rate_item_id" SERIAL NOT NULL, "rate_item_name" character varying(255) NOT NULL, "rate_item_details" text, "rate_season_id" integer NOT NULL, "rate_type_id" integer, "rate_period_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_71a7a616e4e08e5cb981a67a29d" PRIMARY KEY ("rate_item_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_seasons" ("rate_season_id" SERIAL NOT NULL, "season_code" character varying(20) NOT NULL, "season_name" character varying(100), "effective_from" date NOT NULL, "effective_to" date, "daily_charge" numeric(10,6), "rate_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4905d05920b2cc332c18d38740c" PRIMARY KEY ("rate_season_id"))`);
        await queryRunner.query(`CREATE TABLE "rates" ("rate_id" SERIAL NOT NULL, "rate_code" character varying(20) NOT NULL, "rate_name" character varying(100) NOT NULL, "rate_category_id" integer NOT NULL, "rate_card_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ae702d9e018d5546c38d83169a3" UNIQUE ("rate_category_id"), CONSTRAINT "REL_ae702d9e018d5546c38d83169a" UNIQUE ("rate_category_id"), CONSTRAINT "PK_d7364083d5182bb16da1ca51a87" PRIMARY KEY ("rate_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_cards" ("rate_card_id" SERIAL NOT NULL, "rate_card_name" character varying(255) NOT NULL, "underlying_nt_type" character varying(50), "time_definition" character varying(50), "tariff_type_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9d8ad628a473c865364ee336e3b" PRIMARY KEY ("rate_card_id"))`);
        await queryRunner.query(`CREATE TABLE "customer_types" ("customer_type_id" SERIAL NOT NULL, "customer_type_code" character varying(50) NOT NULL, "customer_type_name" character varying(255) NOT NULL, CONSTRAINT "PK_23d467ed391efb085b339347d7e" PRIMARY KEY ("customer_type_id"))`);
        await queryRunner.query(`CREATE TABLE "plans" ("plan_id" SERIAL NOT NULL, "int_plan_code" character varying(50) NOT NULL, "ext_plan_code" character varying(50) NOT NULL, "plan_name" character varying(255) NOT NULL, "effective_from" date NOT NULL, "effective_to" date, "review_date" date, "restricted" boolean NOT NULL DEFAULT false, "contingent" boolean NOT NULL DEFAULT false, "direct_debit_only" boolean NOT NULL DEFAULT false, "ebilling_only" boolean NOT NULL DEFAULT false, "solar_cust_only" boolean NOT NULL DEFAULT false, "ev_only" boolean NOT NULL DEFAULT false, "intrinsic_green" boolean NOT NULL DEFAULT false, "intrinsic_gpp" boolean DEFAULT false, "eligibility_criteria" character varying(500), "price_variation_details" character varying(500), "terms_and_conditions" text NOT NULL, "contract_expiry_details" character varying(500), "fixed_rates" character varying(500), "lowest_rps" numeric(10,2), "factsheet_url" text, "zone_id" integer, "plan_type_id" integer NOT NULL, "distributor_id" integer NOT NULL, "customer_type_id" integer NOT NULL, "rate_card_id" integer NOT NULL, "contract_term_id" integer, "retail_tariff_id" integer, "bill_freq_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_084714de33798c5b96f12725f7e" PRIMARY KEY ("plan_id"))`);
        await queryRunner.query(`CREATE TABLE "retail_tariffs" ("retail_tariff_id" SERIAL NOT NULL, "retail_tariff_code" character varying(50) NOT NULL, "retail_tariff_name" character varying(255) NOT NULL, "sacl_flag" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, "distributor_id" integer, "customer_type_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9abb7c5ad24ce9578525dde8eb0" PRIMARY KEY ("retail_tariff_id"))`);
        await queryRunner.query(`CREATE TABLE "retail_ntc_key_relns" ("retail_ntc_reln_id" SERIAL NOT NULL, "retail_tariff_id" integer NOT NULL, "network_tariff_key_id" integer NOT NULL, CONSTRAINT "PK_d2187bcbc1a555edfdc28054a47" PRIMARY KEY ("retail_ntc_reln_id"))`);
        await queryRunner.query(`CREATE TABLE "network_tariff_keys" ("network_tariff_key_id" SERIAL NOT NULL, "network_tariff_key_code" character varying(50) NOT NULL, CONSTRAINT "PK_12c7a0791b3fad3fd1adebddd0b" PRIMARY KEY ("network_tariff_key_id"))`);
        await queryRunner.query(`CREATE TABLE "ntc_relns" ("ntc_reln_id" SERIAL NOT NULL, "network_tariff_id" integer, "network_tariff_key_id" integer NOT NULL, CONSTRAINT "PK_2d2fbeb595072c0c60c4bee07fe" PRIMARY KEY ("ntc_reln_id"))`);
        await queryRunner.query(`CREATE TABLE "network_tariffs" ("network_tariff_id" SERIAL NOT NULL, "network_tariff_code" character varying(50) NOT NULL, "usage" boolean NOT NULL DEFAULT false, "demand" boolean NOT NULL DEFAULT false, "controlled_load" boolean NOT NULL DEFAULT false, "solar" boolean NOT NULL DEFAULT false, "distributor_id" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6ed65993611a71d2ce3f92a1edd" PRIMARY KEY ("network_tariff_id"))`);
        await queryRunner.query(`CREATE TABLE "distributors" ("distributor_id" SERIAL NOT NULL, "distributor_code" character varying(50) NOT NULL, "distributor_name" character varying(255) NOT NULL, "mirn_prefix" character varying(10), "state_id" integer, CONSTRAINT "PK_593e567ed501d21c9c297f4dc7f" PRIMARY KEY ("distributor_id"))`);
        await queryRunner.query(`CREATE TABLE "state" ("state_id" SERIAL NOT NULL, "state_code" character varying(10) NOT NULL, "state_name" character varying(100) NOT NULL, CONSTRAINT "PK_c6c635621335b860a10c0763e78" PRIMARY KEY ("state_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_timings" ("rate_timing_id" SERIAL NOT NULL, "timing_name" character varying(100) NOT NULL, "description" text, "start_time" character varying(5) NOT NULL, "end_time" character varying(5) NOT NULL, "days_of_week" json NOT NULL, "season" character varying(50) NOT NULL, "plan_id" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_373d655edee177b7475bb668caa" PRIMARY KEY ("rate_timing_id"))`);
        await queryRunner.query(`CREATE TABLE "rate_blocks" ("rate_block_id" SERIAL NOT NULL, "rate_block_name" character varying(100) NOT NULL, "description" text, "start_time" character varying(5) NOT NULL, "end_time" character varying(5) NOT NULL, "days_of_week" json NOT NULL, "rate_per_kwh" numeric(10,4) NOT NULL, "supply_charge_per_day" numeric(10,4) NOT NULL, "rate_type" character varying(50) NOT NULL, "season" character varying(50) NOT NULL, "effective_from" date NOT NULL, "effective_to" date NOT NULL, "priority" integer NOT NULL DEFAULT '1', "is_active" boolean NOT NULL DEFAULT true, "plan_id" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3235ef40ef7fb31e372c3174266" PRIMARY KEY ("rate_block_id"))`);
        await queryRunner.query(`CREATE TABLE "file" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "path" character varying NOT NULL, "type" character varying NOT NULL, "user_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "api_logs" ("id" SERIAL NOT NULL, "method" character varying(10) NOT NULL, "url" character varying(500) NOT NULL, "user_id" character varying(50), "ip_address" character varying(45), "user_agent" character varying(500), "status_code" integer NOT NULL, "response_time_ms" integer NOT NULL, "request_body" text, "response_body" text, "error_message" text, "controller" character varying(100), "action" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ea3f2ad34a2921407593ff4425b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_14968beefa90d7382bfcde82ad" ON "api_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_4eb0f23e0693ad4fec007956db" ON "api_logs" ("status_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_728a0edcc49219ad69e8d0312b" ON "api_logs" ("method", "url") `);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_30e98e8746699fb9af235410aff" FOREIGN KEY ("user_id") REFERENCES "gc_cms_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_term_names" ADD CONSTRAINT "FK_18bcb5fdd1ee1be22c7320d25f0" FOREIGN KEY ("charge_term_id") REFERENCES "charge_terms"("charge_term_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_term_names" ADD CONSTRAINT "FK_59c8fca1825b2f46d5a43ca39e6" FOREIGN KEY ("charge_class_id") REFERENCES "charge_classes"("charge_class_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_types" ADD CONSTRAINT "FK_0cc455c8367d69cce026af32909" FOREIGN KEY ("charge_class_id") REFERENCES "charge_classes"("charge_class_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charge_categories" ADD CONSTRAINT "FK_bf51d56b008a0708ce00883fd48" FOREIGN KEY ("charge_class_id") REFERENCES "charge_classes"("charge_class_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charges" ADD CONSTRAINT "FK_28768bded4439ddf8ecb41a0eec" FOREIGN KEY ("plan_id") REFERENCES "plans"("plan_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charges" ADD CONSTRAINT "FK_50336c72af5b002e313671c6255" FOREIGN KEY ("charge_type_id") REFERENCES "charge_types"("charge_type_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charges" ADD CONSTRAINT "FK_ddfa0e9371895cc082b8539bf89" FOREIGN KEY ("charge_category_id") REFERENCES "charge_categories"("charge_category_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "charges" ADD CONSTRAINT "FK_0532420a065efcacc536506ef32" FOREIGN KEY ("charge_term_id") REFERENCES "charge_terms"("charge_term_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tariff_types" ADD CONSTRAINT "FK_7362c18d296c332e4b0cb886384" FOREIGN KEY ("fuel_type_id") REFERENCES "fuel_types"("fuel_type_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_item_blocks" ADD CONSTRAINT "FK_2fd76daa2c924bd7229ea470a49" FOREIGN KEY ("rate_item_id") REFERENCES "rate_items"("rate_item_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_item_demands" ADD CONSTRAINT "FK_605581eaac2356a1e98ce394f51" FOREIGN KEY ("rate_item_id") REFERENCES "rate_items"("rate_item_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_item_demands" ADD CONSTRAINT "FK_f3a2cc661ef47925993ce806efb" FOREIGN KEY ("measurement_period_id") REFERENCES "rate_periods"("rate_period_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_item_timings" ADD CONSTRAINT "FK_1077e2e2d0913ce82bff087150d" FOREIGN KEY ("rate_item_id") REFERENCES "rate_items"("rate_item_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_types" ADD CONSTRAINT "FK_bcbb31c9d0a916e28e7fc4bdca1" FOREIGN KEY ("rate_class_id") REFERENCES "rate_classes"("rate_class_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_items" ADD CONSTRAINT "FK_f01e739b384aa68a9b4718604a4" FOREIGN KEY ("rate_season_id") REFERENCES "rate_seasons"("rate_season_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_items" ADD CONSTRAINT "FK_f38197c99b2cf47c57ffe4618c8" FOREIGN KEY ("rate_type_id") REFERENCES "rate_types"("rate_type_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_items" ADD CONSTRAINT "FK_35f00389f379d20cc37038dd799" FOREIGN KEY ("rate_period_id") REFERENCES "rate_periods"("rate_period_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_seasons" ADD CONSTRAINT "FK_92618de0d2968268eb1bd11474d" FOREIGN KEY ("rate_id") REFERENCES "rates"("rate_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rates" ADD CONSTRAINT "FK_ae702d9e018d5546c38d83169a3" FOREIGN KEY ("rate_category_id") REFERENCES "rate_categories"("rate_category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rates" ADD CONSTRAINT "FK_fd903bc023ba6fa1de55502e706" FOREIGN KEY ("rate_card_id") REFERENCES "rate_cards"("rate_card_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_cards" ADD CONSTRAINT "FK_69b56d7783fc93db601d7f43832" FOREIGN KEY ("tariff_type_id") REFERENCES "tariff_types"("tariff_type_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plans" ADD CONSTRAINT "FK_51af64e74bc4924f926133b0dbf" FOREIGN KEY ("zone_id") REFERENCES "zones"("zone_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plans" ADD CONSTRAINT "FK_b5ac348ffd0099f35bb527c2ad1" FOREIGN KEY ("plan_type_id") REFERENCES "plan_types"("plan_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plans" ADD CONSTRAINT "FK_5ec47f34a4a49dd15cea40392fd" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("distributor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plans" ADD CONSTRAINT "FK_36fa24d547470d2533471ad0880" FOREIGN KEY ("customer_type_id") REFERENCES "customer_types"("customer_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plans" ADD CONSTRAINT "FK_4d32323c3cf93c4290ca5d051d0" FOREIGN KEY ("rate_card_id") REFERENCES "rate_cards"("rate_card_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plans" ADD CONSTRAINT "FK_2032c1a72ab5ac9330bb39e7599" FOREIGN KEY ("retail_tariff_id") REFERENCES "retail_tariffs"("retail_tariff_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retail_tariffs" ADD CONSTRAINT "FK_28268ce38ae7d936e7626318e52" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("distributor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retail_tariffs" ADD CONSTRAINT "FK_4d0fb0dab3cbfd161efa612230e" FOREIGN KEY ("customer_type_id") REFERENCES "customer_types"("customer_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retail_ntc_key_relns" ADD CONSTRAINT "FK_8d99c43b3c55d8acd230aa768c6" FOREIGN KEY ("retail_tariff_id") REFERENCES "retail_tariffs"("retail_tariff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "retail_ntc_key_relns" ADD CONSTRAINT "FK_4344b1ffb74e4878d8ca26c6886" FOREIGN KEY ("network_tariff_key_id") REFERENCES "network_tariff_keys"("network_tariff_key_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ntc_relns" ADD CONSTRAINT "FK_98b8be76df3322f6bf93a9417c5" FOREIGN KEY ("network_tariff_id") REFERENCES "network_tariffs"("network_tariff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ntc_relns" ADD CONSTRAINT "FK_db7da37c4ca0d0d18ad991ae915" FOREIGN KEY ("network_tariff_key_id") REFERENCES "network_tariff_keys"("network_tariff_key_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "network_tariffs" ADD CONSTRAINT "FK_dac485d5da4251cc15aa7d0d4ad" FOREIGN KEY ("distributor_id") REFERENCES "distributors"("distributor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "distributors" ADD CONSTRAINT "FK_86f1e4a42fa1a3840f004529e63" FOREIGN KEY ("state_id") REFERENCES "state"("state_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_timings" ADD CONSTRAINT "FK_9803a3152dc1f4d726db64ea3d6" FOREIGN KEY ("plan_id") REFERENCES "plans"("plan_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rate_blocks" ADD CONSTRAINT "FK_747b694fbccf26335adfc802a1d" FOREIGN KEY ("plan_id") REFERENCES "plans"("plan_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file" ADD CONSTRAINT "FK_516f1cf15166fd07b732b4b6ab0" FOREIGN KEY ("user_id") REFERENCES "gc_cms_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "file" DROP CONSTRAINT "FK_516f1cf15166fd07b732b4b6ab0"`);
        await queryRunner.query(`ALTER TABLE "rate_blocks" DROP CONSTRAINT "FK_747b694fbccf26335adfc802a1d"`);
        await queryRunner.query(`ALTER TABLE "rate_timings" DROP CONSTRAINT "FK_9803a3152dc1f4d726db64ea3d6"`);
        await queryRunner.query(`ALTER TABLE "distributors" DROP CONSTRAINT "FK_86f1e4a42fa1a3840f004529e63"`);
        await queryRunner.query(`ALTER TABLE "network_tariffs" DROP CONSTRAINT "FK_dac485d5da4251cc15aa7d0d4ad"`);
        await queryRunner.query(`ALTER TABLE "ntc_relns" DROP CONSTRAINT "FK_db7da37c4ca0d0d18ad991ae915"`);
        await queryRunner.query(`ALTER TABLE "ntc_relns" DROP CONSTRAINT "FK_98b8be76df3322f6bf93a9417c5"`);
        await queryRunner.query(`ALTER TABLE "retail_ntc_key_relns" DROP CONSTRAINT "FK_4344b1ffb74e4878d8ca26c6886"`);
        await queryRunner.query(`ALTER TABLE "retail_ntc_key_relns" DROP CONSTRAINT "FK_8d99c43b3c55d8acd230aa768c6"`);
        await queryRunner.query(`ALTER TABLE "retail_tariffs" DROP CONSTRAINT "FK_4d0fb0dab3cbfd161efa612230e"`);
        await queryRunner.query(`ALTER TABLE "retail_tariffs" DROP CONSTRAINT "FK_28268ce38ae7d936e7626318e52"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP CONSTRAINT "FK_2032c1a72ab5ac9330bb39e7599"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP CONSTRAINT "FK_4d32323c3cf93c4290ca5d051d0"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP CONSTRAINT "FK_36fa24d547470d2533471ad0880"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP CONSTRAINT "FK_5ec47f34a4a49dd15cea40392fd"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP CONSTRAINT "FK_b5ac348ffd0099f35bb527c2ad1"`);
        await queryRunner.query(`ALTER TABLE "plans" DROP CONSTRAINT "FK_51af64e74bc4924f926133b0dbf"`);
        await queryRunner.query(`ALTER TABLE "rate_cards" DROP CONSTRAINT "FK_69b56d7783fc93db601d7f43832"`);
        await queryRunner.query(`ALTER TABLE "rates" DROP CONSTRAINT "FK_fd903bc023ba6fa1de55502e706"`);
        await queryRunner.query(`ALTER TABLE "rates" DROP CONSTRAINT "FK_ae702d9e018d5546c38d83169a3"`);
        await queryRunner.query(`ALTER TABLE "rate_seasons" DROP CONSTRAINT "FK_92618de0d2968268eb1bd11474d"`);
        await queryRunner.query(`ALTER TABLE "rate_items" DROP CONSTRAINT "FK_35f00389f379d20cc37038dd799"`);
        await queryRunner.query(`ALTER TABLE "rate_items" DROP CONSTRAINT "FK_f38197c99b2cf47c57ffe4618c8"`);
        await queryRunner.query(`ALTER TABLE "rate_items" DROP CONSTRAINT "FK_f01e739b384aa68a9b4718604a4"`);
        await queryRunner.query(`ALTER TABLE "rate_types" DROP CONSTRAINT "FK_bcbb31c9d0a916e28e7fc4bdca1"`);
        await queryRunner.query(`ALTER TABLE "rate_item_timings" DROP CONSTRAINT "FK_1077e2e2d0913ce82bff087150d"`);
        await queryRunner.query(`ALTER TABLE "rate_item_demands" DROP CONSTRAINT "FK_f3a2cc661ef47925993ce806efb"`);
        await queryRunner.query(`ALTER TABLE "rate_item_demands" DROP CONSTRAINT "FK_605581eaac2356a1e98ce394f51"`);
        await queryRunner.query(`ALTER TABLE "rate_item_blocks" DROP CONSTRAINT "FK_2fd76daa2c924bd7229ea470a49"`);
        await queryRunner.query(`ALTER TABLE "tariff_types" DROP CONSTRAINT "FK_7362c18d296c332e4b0cb886384"`);
        await queryRunner.query(`ALTER TABLE "charges" DROP CONSTRAINT "FK_0532420a065efcacc536506ef32"`);
        await queryRunner.query(`ALTER TABLE "charges" DROP CONSTRAINT "FK_ddfa0e9371895cc082b8539bf89"`);
        await queryRunner.query(`ALTER TABLE "charges" DROP CONSTRAINT "FK_50336c72af5b002e313671c6255"`);
        await queryRunner.query(`ALTER TABLE "charges" DROP CONSTRAINT "FK_28768bded4439ddf8ecb41a0eec"`);
        await queryRunner.query(`ALTER TABLE "charge_categories" DROP CONSTRAINT "FK_bf51d56b008a0708ce00883fd48"`);
        await queryRunner.query(`ALTER TABLE "charge_types" DROP CONSTRAINT "FK_0cc455c8367d69cce026af32909"`);
        await queryRunner.query(`ALTER TABLE "charge_term_names" DROP CONSTRAINT "FK_59c8fca1825b2f46d5a43ca39e6"`);
        await queryRunner.query(`ALTER TABLE "charge_term_names" DROP CONSTRAINT "FK_18bcb5fdd1ee1be22c7320d25f0"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_30e98e8746699fb9af235410aff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_728a0edcc49219ad69e8d0312b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4eb0f23e0693ad4fec007956db"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_14968beefa90d7382bfcde82ad"`);
        await queryRunner.query(`DROP TABLE "api_logs"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP TABLE "rate_blocks"`);
        await queryRunner.query(`DROP TABLE "rate_timings"`);
        await queryRunner.query(`DROP TABLE "state"`);
        await queryRunner.query(`DROP TABLE "distributors"`);
        await queryRunner.query(`DROP TABLE "network_tariffs"`);
        await queryRunner.query(`DROP TABLE "ntc_relns"`);
        await queryRunner.query(`DROP TABLE "network_tariff_keys"`);
        await queryRunner.query(`DROP TABLE "retail_ntc_key_relns"`);
        await queryRunner.query(`DROP TABLE "retail_tariffs"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TABLE "customer_types"`);
        await queryRunner.query(`DROP TABLE "rate_cards"`);
        await queryRunner.query(`DROP TABLE "rates"`);
        await queryRunner.query(`DROP TABLE "rate_seasons"`);
        await queryRunner.query(`DROP TABLE "rate_items"`);
        await queryRunner.query(`DROP TABLE "rate_types"`);
        await queryRunner.query(`DROP TABLE "rate_classes"`);
        await queryRunner.query(`DROP TABLE "rate_item_timings"`);
        await queryRunner.query(`DROP TABLE "rate_item_demands"`);
        await queryRunner.query(`DROP TABLE "rate_periods"`);
        await queryRunner.query(`DROP TABLE "rate_item_blocks"`);
        await queryRunner.query(`DROP TABLE "rate_categories"`);
        await queryRunner.query(`DROP TABLE "tariff_types"`);
        await queryRunner.query(`DROP TABLE "fuel_types"`);
        await queryRunner.query(`DROP TABLE "zones"`);
        await queryRunner.query(`DROP TABLE "plan_types"`);
        await queryRunner.query(`DROP TABLE "charges"`);
        await queryRunner.query(`DROP TABLE "charge_categories"`);
        await queryRunner.query(`DROP TABLE "charge_classes"`);
        await queryRunner.query(`DROP TABLE "charge_types"`);
        await queryRunner.query(`DROP TABLE "charge_term_names"`);
        await queryRunner.query(`DROP TABLE "charge_terms"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30e98e8746699fb9af235410af"`);
        await queryRunner.query(`DROP TABLE "session"`);
        await queryRunner.query(`DROP TABLE "gc_cms_users"`);
    }

}
