export enum FileType {
  SELFIE = 'SELFIE',
  ID_CARD = 'ID_CARD',
  SALARY_SLIP = 'SALARY_SLIP',
  BANK_STATEMENT = 'BANK_STATEMENT',
  UTILITY_BILL = 'UTILITY_BILL',
  PROFILE_IMAGE = 'PROFILE_IMAGE',
}
