export const TABLES = {
  test: 'test',
  state: 'state',
  store: 'store',
  cache: 'cache',
  razorPay: 'razor_pay',
  razorPayTransactions: 'razor_pay_transactions',
  logger: 'api_logger',
  appBaseCamp: 'base_camp',
  appArmedForceBranch: 'armed_force_branches',
  appCategory: 'categories',
  appUser: 'users',
  cmsUserCategory: 'gc_cms_user_categories',
  video: 'video',
  videoPermissions: 'video_permissions',
  communication: 'communication',
  article: 'articles',
  encryption: 'encryption',
  sns: 'sns',
  otp: 'otp',
  lookup: 'lookup',
  lookup_categories: 'lookup_categories',
  ocr: 'ocr',
  file: 'file',
  session: 'session',
  reasons: 'user_status_reasons',
  user: 'gc_cms_users',
  userFollow: 'follow',
  userDevice: 'user_device',
  notifications: 'notifications',
  responseMessages: 'response_messages',
  notificationTokens: 'notification_tokens',
  roles: 'gc_cms_roles',
  permissions: 'gc_cms_permissions',
  role_permissions: 'gc_cms_role_permissions',
  rejectionResons: 'rejection_resons',
  reSubmissionReasons: 'resubmission_reasons',
  governmentConnectMessage: 'government_connect_message',
  familyMember: 'family_members',
  categories: 'categories',
  userRole: 'gc_cms_user_roles',
  tags: 'gc_cms_tags',

  retailTariff: 'retail_tariffs',
  retailNtcKeyReln: 'retail_ntc_key_relns',
  customerType: 'customer_types',
  distributor: 'distributors',
  networkTariff: 'network_tariffs',
  networkTariffKey: 'network_tariff_keys',
  ntcReln: 'ntc_relns',
};

export const EVENTS = {
  userLoggedIn: 'user.loggedIn',
  userRequestRegistered: 'user.requestRegistered',
  userStatusUpdated: 'user.statusUpdated',
};
